# Generated by Django 3.0.3 on 2020-10-26 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(choices=[('Love-Comedy', 'Love-Comedy'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Drama', 'Drama'), ('Romance', 'Romance')], default='Love-Comedy', max_length=100)),
                ('date', models.DateField(max_length=200)),
                ('commentation', models.CharField(max_length=200)),
                ('status_ongoing', models.BooleanField(default=True)),
                ('favor', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
