# Generated by Django 3.0.3 on 2020-10-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_review', '0003_auto_20201026_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='allboard',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
